name: Deploy Backend to GKE

on:
  push:
    branches: [main]

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    name: Build & Deploy Backend
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud using OIDC
      uses: google-github-actions/auth@v2
      with:
        token_format: 'access_token'
        workload_identity_provider: 'projects/97909975143/locations/global/workloadIdentityPools/github-workload-identity/providers/github-provider'
        service_account: 'github-deployer@my-three-tier-app-466909.iam.gserviceaccount.com'

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v1

    - name: Install GKE Auth Plugin
      run: |
        gcloud components install gke-gcloud-auth-plugin --quiet

    - name: Configure Docker for Artifact Registry
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev --quiet

    - name: Build & Push Docker Image
      run: |
        docker build -t us-central1-docker.pkg.dev/my-three-tier-app-466909/backend-repo/backend:latest .
        docker push us-central1-docker.pkg.dev/my-three-tier-app-466909/backend-repo/backend:latest

    - name: Get GKE Credentials
      run: |
        gcloud container clusters get-credentials gke-github-cluster --region us-central1

    - name: Create Firebase Key Secret
      run: |
        echo "${{ secrets.FIREBASE_KEY }}" | base64 -d > firebase_key.json
        kubectl delete secret firebase-key --ignore-not-found
        kubectl create secret generic firebase-key \
          --from-file=firebase_key.json
        rm firebase_key.json

    - name: Create JWT Secret
      run: |
        kubectl delete secret backend-secrets --ignore-not-found
        kubectl create secret generic backend-secrets \
          --from-literal=JWT_SECRET="${{ secrets.JWT_SECRET }}" 

    - name: Deploy Backend to GKE
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
